/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.examplejpa.view;

import co.edu.sena.examplejpa.controller.EmployeeTypeController;
import co.edu.sena.examplejpa.controller.IEmployeeTypeController;
import co.edu.sena.examplejpa.model.EmployeeType;
import co.edu.sena.examplejpa.utils.MessageUtils;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * date:05/04/2025
 * @author Esteban Colorado Vargas
 * objetivo: crear la vista para EmployeeType
 */
public class JFrameEmployeeType extends javax.swing.JFrame {
    
    private final IEmployeeTypeController employeeTypeController = new EmployeeTypeController();
    int xMouse;
    int yMouse;

    /**
     * Creates new form JFrameEmployeeTypeModified
     */
    public JFrameEmployeeType() {
        initComponents();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jLabeltTitle = new javax.swing.JLabel();
        jLabelDescript1 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDescript = new javax.swing.JTextField();
        jButtonCleart = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployeeType = new javax.swing.JTable();
        jPanelCloseWindow = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeltTitle.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jLabeltTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltTitle.setText("CREAR TIPO EMPLEADO");
        jPanelBackground.add(jLabeltTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 770, -1));

        jLabelDescript1.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabelDescript1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescript1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescript1.setText("Aqui  puedes insertar, actualizar, eliminar y consultar todo lo referente a la tabla empleado.");
        jPanelBackground.add(jLabelDescript1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 770, -1));

        jLabelId.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("ID:");
        jPanelBackground.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jTextFieldId.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jPanelBackground.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 180, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESCRIPCION:");
        jPanelBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jTextFieldDescript.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jPanelBackground.add(jTextFieldDescript, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 180, -1));

        jButtonCleart.setBackground(new java.awt.Color(0, 204, 204));
        jButtonCleart.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jButtonCleart.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCleart.setText("LIMPIAR");
        jButtonCleart.setBorderPainted(false);
        jButtonCleart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCleart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCleart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleartActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonCleart, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 120, -1));

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("ELIMINAR");
        jButtonDelete.setBorderPainted(false);
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 120, -1));

        jButtonUpdate.setBackground(new java.awt.Color(102, 102, 255));
        jButtonUpdate.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("ACTUALIZAR");
        jButtonUpdate.setAlignmentX(0.5F);
        jButtonUpdate.setBorderPainted(false);
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 120, -1));

        jButtonInsert.setBackground(new java.awt.Color(0, 255, 0));
        jButtonInsert.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jButtonInsert.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert.setText("INSERTAR");
        jButtonInsert.setBorderPainted(false);
        jButtonInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 120, -1));

        jTableEmployeeType.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTableEmployeeType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEmployeeType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmployeeTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmployeeType);

        jPanelBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 750, 200));

        jPanelCloseWindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/examplejpa/view/Icono de Home.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseWindowLayout = new javax.swing.GroupLayout(jPanelCloseWindow);
        jPanelCloseWindow.setLayout(jPanelCloseWindowLayout);
        jPanelCloseWindowLayout.setHorizontalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCloseWindowLayout.setVerticalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanelBackground.add(jPanelCloseWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/examplejpa/view/background para pestañas.png"))); // NOI18N
        jPanelBackground.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 490));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelBackground.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCleartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleartActionPerformed
        // BOTON LIMPIAR
        clear();
    }//GEN-LAST:event_jButtonCleartActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // BOTON PARA ELIMINAR
        try {
            int option = JOptionPane.showConfirmDialog(rootPane,"estas seguro de eliminar el resgistro?",
                "CONFIRMAR", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                employeeTypeController.delete(Integer.parseInt(jTextFieldId.getText()));
                MessageUtils.showInfoMessage("empleado eliminado correctamente...");
                fillTable();
            }
            clear();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("HUBO UN ERROR al eliminar..." + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // ACTULIZAR
        try {
            EmployeeType employeeType = new EmployeeType();
            employeeType.setId(Integer.parseInt(jTextFieldId.getText()));
            employeeType.setDescript(jTextFieldDescript.getText().toUpperCase());
            employeeTypeController.update(employeeType);
            MessageUtils.showInfoMessage("empleado actualizado exitosamente...");
            fillTable();
            clear();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("HUBO UN ERROR al actualizar..." + e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // BOTON PARA INSERTAR
        try {
            EmployeeType employeeType = new EmployeeType();
            employeeType.setDescript(jTextFieldDescript.getText().toUpperCase());
            employeeTypeController.insert(employeeType);
            MessageUtils.showInfoMessage("empleado creado exitosamente...");
            fillTable();
            clear();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("HUBO UN ERROR al insertar..." +e.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jTableEmployeeTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmployeeTypeMouseClicked
        // EVENTO PARA LA TABLA
        int rowSelected = jTableEmployeeType.getSelectedRow();
        if(rowSelected != -1) {
            String idSelected = jTableEmployeeType.getValueAt(rowSelected, 0).toString();
            String descriptionSelected = jTableEmployeeType.getValueAt(rowSelected, 1).toString();

            jTextFieldId.setText(idSelected);
            jTextFieldDescript.setText(descriptionSelected);
            jButtonInsert.setEnabled(false);
            jButtonDelete.setEnabled(true);
            jButtonUpdate.setEnabled(true);
        }
    }//GEN-LAST:event_jTableEmployeeTypeMouseClicked

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        // EVENTO COMPLEMETNARIO PARA MOVER LA PESTAÑA
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        // EVENTO PARA MOVER LA PESTAÑA
        int xPosition = evt.getXOnScreen();
        int yPosition = evt.getYOnScreen();
        
        this.setLocation(xPosition - xMouse, yPosition - yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // EVENTO PARA CERRAR EL PROGRAMA
        int option = JOptionPane.showConfirmDialog(rootPane, 
                "Quieres volver a el menu principal?", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        
        if(option == JOptionPane.YES_OPTION) {
            new JFrameMenu().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // BOTON PARA EFECTO HOVER
        jPanelCloseWindow.setBackground(Color.red);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // BOTON PARA EFECTO HOVER DE SALIDA
        jPanelCloseWindow.setBackground(Color.white);
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmployeeType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmployeeType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmployeeType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmployeeType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmployeeType().setVisible(true);
            }
        });
    }
    
    public void clear() {
        jTextFieldId.setText("");
        jTextFieldDescript.setText("");
        jButtonInsert.setEnabled(true);
        jButtonDelete.setEnabled(false);
        jButtonUpdate.setEnabled(false);
    }

    public void fillTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            jTableEmployeeType.setModel(model);
            model.addColumn("id");
            model.addColumn("Descripcion");

            String[] rows = new String[2];
            List<EmployeeType> types = employeeTypeController.findAll();
            for (EmployeeType type : types) {
                rows[0] = String.valueOf(type.getId());
                rows[1] = type.getDescript();
                model.addRow(rows);
            }
            jButtonInsert.setEnabled(true);
            jButtonUpdate.setEnabled(false);
            jButtonDelete.setEnabled(false);
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error" + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCleart;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelDescript1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabeltTitle;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelCloseWindow;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployeeType;
    private javax.swing.JTextField jTextFieldDescript;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables
}
