/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.examplejpa.view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * date: 06/04/2025
 * @author Esteban Colorado Vargas
 * objetivo: crear la vista de un menu para abrir otras pestañas
 */
public class JFrameMenu extends javax.swing.JFrame {
    
    int xMouse;
    int yMouse;

    /**
     * Creates new form JFrameMenu
     */
    public JFrameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelCloseWindow = new javax.swing.JPanel();
        jLabelCloseWindow = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jButtonCloseProgram = new javax.swing.JButton();
        jButtonEmployee = new javax.swing.JButton();
        jButtonKeys = new javax.swing.JButton();
        jButtonEmployeeType = new javax.swing.JButton();
        jButtonRecord1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/examplejpa/view/logo para master key-modified.png"))); // NOI18N
        jPanel2.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 270, 490));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/examplejpa/view/Sin título.png"))); // NOI18N
        jPanel2.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 270, 490));

        jLabelTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("¡BIENVENID@ A MASTER KEY!");
        jPanel2.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 500, -1));

        jPanelCloseWindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCloseWindow.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelCloseWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseWindow.setText("X");
        jLabelCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseWindowLayout = new javax.swing.GroupLayout(jPanelCloseWindow);
        jPanelCloseWindow.setLayout(jPanelCloseWindowLayout);
        jPanelCloseWindowLayout.setHorizontalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanelCloseWindowLayout.setVerticalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCloseWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelCloseWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 50));

        jButtonCloseProgram.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCloseProgram.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 18)); // NOI18N
        jButtonCloseProgram.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCloseProgram.setText("CERRAR PROGRAMA");
        jButtonCloseProgram.setBorderPainted(false);
        jButtonCloseProgram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCloseProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseProgramActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCloseProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 200, 40));

        jButtonEmployee.setBackground(new java.awt.Color(0, 62, 139));
        jButtonEmployee.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 18)); // NOI18N
        jButtonEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmployee.setText("EMPLEADO");
        jButtonEmployee.setBorderPainted(false);
        jButtonEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 40));

        jButtonKeys.setBackground(new java.awt.Color(0, 62, 139));
        jButtonKeys.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 18)); // NOI18N
        jButtonKeys.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKeys.setText("LLAVES");
        jButtonKeys.setBorderPainted(false);
        jButtonKeys.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeysActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonKeys, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 40));

        jButtonEmployeeType.setBackground(new java.awt.Color(0, 62, 139));
        jButtonEmployeeType.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 18)); // NOI18N
        jButtonEmployeeType.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEmployeeType.setText("TIPO DE EMPLEADO");
        jButtonEmployeeType.setBorderPainted(false);
        jButtonEmployeeType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEmployeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeTypeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEmployeeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 200, 40));

        jButtonRecord1.setBackground(new java.awt.Color(0, 62, 139));
        jButtonRecord1.setFont(new java.awt.Font("Roboto Condensed ExtraBold", 0, 18)); // NOI18N
        jButtonRecord1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecord1.setText("REGISTROS");
        jButtonRecord1.setBorderPainted(false);
        jButtonRecord1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecord1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRecord1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseClicked
        // EVENTO PARA CERRAR EL PROGRAMA
        int option = JOptionPane.showConfirmDialog(rootPane, 
                "Estas seguro de salir?", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        
        if(option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabelCloseWindowMouseClicked

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        // EVENTO COMPLEMETNARIO PARA MOVER LA PESTAÑA
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        // EVENTO PARA MOVER LA PESTAÑA
        int xPosition = evt.getXOnScreen();
        int yPosition = evt.getYOnScreen();
        
        this.setLocation(xPosition - xMouse, yPosition - yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jLabelCloseWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseEntered
        // BOTON EFECTO HOVER
        jPanelCloseWindow.setBackground(Color.red);
    }//GEN-LAST:event_jLabelCloseWindowMouseEntered

    private void jLabelCloseWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseExited
        // TBOTON PARA EFECTO HOVER DE SALIDA
        jPanelCloseWindow.setBackground(Color.white);
    }//GEN-LAST:event_jLabelCloseWindowMouseExited

    private void jButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeActionPerformed
        // BOTON PARA ABRIR EL FRAME DE EMPLOYEE
        showWindow(new JFrameEmployee());
    }//GEN-LAST:event_jButtonEmployeeActionPerformed

    private void jButtonEmployeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeTypeActionPerformed
        // BOTON PARA ABRIR EL FRAME DE EMPLOYEETYPE
        showWindow(new JFrameEmployeeType());
    }//GEN-LAST:event_jButtonEmployeeTypeActionPerformed

    private void jButtonCloseProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseProgramActionPerformed
        // BOTON PARA CERRAR EL PROGRAMA
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseProgramActionPerformed

    private void jButtonKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeysActionPerformed
        // BOTON PARA ABRIR EL FRAME DE KEY
        showWindow(new JFrameKeyRoom());
    }//GEN-LAST:event_jButtonKeysActionPerformed

    private void jButtonRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecord1ActionPerformed
        // BOTON PARA MOSTRAR EL FRAME RECORD
        showWindow(new JFrameRecord());
    }//GEN-LAST:event_jButtonRecord1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenu().setVisible(true);
            }
        });
    }
    
    public void showWindow(JFrame frameToShow) {
        frameToShow.setVisible(true);
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCloseProgram;
    private javax.swing.JButton jButtonEmployee;
    private javax.swing.JButton jButtonEmployeeType;
    private javax.swing.JButton jButtonKeys;
    private javax.swing.JButton jButtonRecord1;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelCloseWindow;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCloseWindow;
    private javax.swing.JPanel jPanelHeader;
    // End of variables declaration//GEN-END:variables
}
