/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.sena.examplejpa.view;

import co.edu.sena.examplejpa.controller.IEmployeeController;
import co.edu.sena.examplejpa.controller.EmployeeController;
import co.edu.sena.examplejpa.controller.EmployeeTypeController;
import co.edu.sena.examplejpa.controller.IEmployeeTypeController;
import co.edu.sena.examplejpa.model.Employee;
import co.edu.sena.examplejpa.model.EmployeeType;
import co.edu.sena.examplejpa.utils.MessageUtils;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * date: 05/04/2025
 * @author Esteban Colorado Vargas
 * objetivo: crear la vista para Employee
 */
public class JFrameEmployee extends javax.swing.JFrame {
    private final IEmployeeController employeeController = new EmployeeController();
    private final IEmployeeTypeController employeeTypeController = new EmployeeTypeController();
    int xMouse;
    int yMouse;
    
    /**
     * Creates new form JFrameEmployeeModified
     */
    public JFrameEmployee() {
        initComponents();
        fillTable();
        fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployee = new javax.swing.JTable();
        jLabelDocument = new javax.swing.JLabel();
        jTextFieldDocument = new javax.swing.JTextField();
        jTextFieldFullName = new javax.swing.JTextField();
        jLabelFullName = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabelPhone = new javax.swing.JLabel();
        jLabelType_id = new javax.swing.JLabel();
        jComboBoxType_id = new javax.swing.JComboBox<>();
        jTextFieldPhone = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCleart = new javax.swing.JButton();
        jLabelDescript = new javax.swing.JLabel();
        jLabeltTitle = new javax.swing.JLabel();
        jPanelCloseWindow = new javax.swing.JPanel();
        jLabelCloseWindow = new javax.swing.JLabel();
        jLabelBackGround = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEmployee.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmployee);

        jPanelBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 750, 170));

        jLabelDocument.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabelDocument.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDocument.setText("DOCUMENTO:");
        jPanelBackground.add(jLabelDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jTextFieldDocument.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jPanelBackground.add(jTextFieldDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, -1));

        jTextFieldFullName.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jPanelBackground.add(jTextFieldFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 200, -1));

        jLabelFullName.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabelFullName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFullName.setText("NOMBRE COMPLETO:");
        jPanelBackground.add(jLabelFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabelAddress.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddress.setText("DIRECCION:");
        jPanelBackground.add(jLabelAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        jTextFieldAddress.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jPanelBackground.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, -1));

        jLabelPhone.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabelPhone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhone.setText("TELEFONO:");
        jPanelBackground.add(jLabelPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabelType_id.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabelType_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabelType_id.setText("TIPO DE EMPLEADO:");
        jPanelBackground.add(jLabelType_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jComboBoxType_id.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jPanelBackground.add(jComboBoxType_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 200, -1));

        jTextFieldPhone.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        jPanelBackground.add(jTextFieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 200, -1));

        jButtonInsert.setBackground(new java.awt.Color(0, 255, 0));
        jButtonInsert.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButtonInsert.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert.setText("INSERTAR");
        jButtonInsert.setBorderPainted(false);
        jButtonInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 120, -1));

        jButtonUpdate.setBackground(new java.awt.Color(102, 102, 255));
        jButtonUpdate.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("ACTUALIZAR");
        jButtonUpdate.setBorderPainted(false);
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 120, -1));

        jButtonDelete.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDelete.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("ELIMINAR");
        jButtonDelete.setBorderPainted(false);
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 120, -1));

        jButtonCleart.setBackground(new java.awt.Color(0, 204, 204));
        jButtonCleart.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButtonCleart.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCleart.setText("LIMPIAR");
        jButtonCleart.setBorderPainted(false);
        jButtonCleart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCleart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleartActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonCleart, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 120, -1));

        jLabelDescript.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabelDescript.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescript.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescript.setText("Aqui  puedes insertar, actualizar, eliminar y consultar todo lo referente a la tabla empleado.");
        jPanelBackground.add(jLabelDescript, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 770, -1));

        jLabeltTitle.setFont(new java.awt.Font("Roboto Condensed", 1, 20)); // NOI18N
        jLabeltTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeltTitle.setText("CREAR EMPLEADO");
        jPanelBackground.add(jLabeltTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 770, -1));

        jPanelCloseWindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCloseWindow.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabelCloseWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCloseWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/examplejpa/view/Icono de Home.png"))); // NOI18N
        jLabelCloseWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCloseWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseWindowMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelCloseWindowLayout = new javax.swing.GroupLayout(jPanelCloseWindow);
        jPanelCloseWindow.setLayout(jPanelCloseWindowLayout);
        jPanelCloseWindowLayout.setHorizontalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCloseWindowLayout.createSequentialGroup()
                .addComponent(jLabelCloseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCloseWindowLayout.setVerticalGroup(
            jPanelCloseWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCloseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelBackground.add(jPanelCloseWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabelBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/sena/examplejpa/view/background para pestañas.png"))); // NOI18N
        jLabelBackGround.setMaximumSize(new java.awt.Dimension(770, 490));
        jLabelBackGround.setMinimumSize(new java.awt.Dimension(770, 490));
        jPanelBackground.add(jLabelBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 490));

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelHeaderMouseDragged(evt);
            }
        });
        jPanelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelHeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanelBackground.add(jPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMouseDragged
        // EVENTO PARA MOVER LA PESTAÑA
        int xPosition = evt.getXOnScreen();
        int yPosition = evt.getYOnScreen();
        
        this.setLocation(xPosition - xMouse, yPosition - yMouse);
    }//GEN-LAST:event_jPanelHeaderMouseDragged

    private void jPanelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelHeaderMousePressed
        // EVENTO COMPLEMETNARIO PARA MOVER LA PESTAÑA
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanelHeaderMousePressed

    private void jLabelCloseWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseClicked
        // EVENTO PARA CERRAR EL PROGRAMA
        int option = JOptionPane.showConfirmDialog(rootPane, 
                "Quieres volver a el menu principal?", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        
        if(option == JOptionPane.YES_OPTION) {
            new JFrameMenu().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jLabelCloseWindowMouseClicked

    private void jLabelCloseWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseEntered
        // BOTON EFECTO HOVER
        jPanelCloseWindow.setBackground(Color.RED);
    }//GEN-LAST:event_jLabelCloseWindowMouseEntered

    private void jLabelCloseWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseWindowMouseExited
        // TBOTON PARA EFECTO HOVER DE SALIDA
        jPanelCloseWindow.setBackground(Color.white);
    }//GEN-LAST:event_jLabelCloseWindowMouseExited

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // BOTON PARA INSERTAR
        try {
            Employee employee = new Employee();
            employee.setDocument(Long.valueOf(jTextFieldDocument.getText()));
            employee.setFullname(jTextFieldFullName.getText());
            employee.setDireccion(jTextFieldAddress.getText());
            employee.setTelefono(jTextFieldPhone.getText());
            employee.setTypeId((EmployeeType) jComboBoxType_id.getSelectedItem());
            employeeController.insert(employee);
            MessageUtils.showInfoMessage("El empleado se ha añadido correctamente...");
            fillTable();
            clear();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al insertar el usuario..."
                + e.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // ACTULIZAR
        try {
            Employee employee = new Employee();
            employee.setDocument(Long.valueOf(jTextFieldDocument.getText()));
            employee.setFullname(jTextFieldFullName.getText());
            employee.setDireccion(jTextFieldAddress.getText());
            employee.setTelefono(jTextFieldPhone.getText());
            employee.setTypeId((EmployeeType) jComboBoxType_id.getSelectedItem());
            employeeController.update(employee);
            MessageUtils.showInfoMessage("El empleado se ha actualizado correctamente...");
            fillTable();
            clear();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al actualizar el empleado..."
                + e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // BOTON PARA ELIMINAR
        try {
            int option = JOptionPane.showConfirmDialog(rootPane,"Estas seguro de eliminar el empleado?",
                "CONFIRMAR", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                employeeController.delete(Long.valueOf(jTextFieldDocument.getText()));
                MessageUtils.showInfoMessage("Empleado eliminado correctamente...");
                fillTable();
            }
            clear();
        } catch (Exception e) {
            MessageUtils.showErrorMessage("HUBO UN ERROR al eliminar..." + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCleartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleartActionPerformed
        // BOTON LIMPIAR
        clear();
    }//GEN-LAST:event_jButtonCleartActionPerformed

    private void jTableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmployeeMouseClicked
        // EVENTO PARA EL CLICK EN LA TABLA
        int rowSelected = jTableEmployee.getSelectedRow();
        if (rowSelected != -1) {
            Long documentSelected = Long.valueOf(jTableEmployee.getValueAt(rowSelected, 0).toString());
            try {
                Employee employee = employeeController.findById(documentSelected);
                jTextFieldDocument.setText(String.valueOf(documentSelected));
                jTextFieldFullName.setText(employee.getFullname());
                jTextFieldAddress.setText(employee.getDireccion());
                jTextFieldPhone.setText(employee.getTelefono());
                jComboBoxType_id.getModel().setSelectedItem(employee.getTypeId());
            } catch (Exception e) {
                MessageUtils.showErrorMessage("ERROR al usar el evento de click"
                    + e.getMessage());
            }
        }
        jButtonInsert.setEnabled(false);
        jButtonDelete.setEnabled(true);
        jButtonUpdate.setEnabled(true);
    }//GEN-LAST:event_jTableEmployeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmployee().setVisible(true);
            }
        });
    }
    
    public void fillTable() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            jTableEmployee.setModel(model);
            model.addColumn("documento");
            model.addColumn("Nombre Completo");
            model.addColumn("Tipo de empleado");

            String[] rows = new String[3];
            List<Employee> types = employeeController.findAll();
            for (Employee type : types) {
                rows[0] = String.valueOf(type.getDocument());
                rows[1] = type.getFullname();
                rows[2] = type.getTypeId().getDescript();
                model.addRow(rows);
            }
            jButtonInsert.setEnabled(true);
            jButtonUpdate.setEnabled(false);
            jButtonDelete.setEnabled(false);
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido un error al llenar la tabla..."
                    + e.getMessage());
        }
    }
    
    private void fillComboBox() {
        try {
            List<EmployeeType> allTypes = employeeTypeController.findAll();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            jComboBoxType_id.setModel(model);
            model.addAll(allTypes);
            jComboBoxType_id.setSelectedIndex(0);
        } catch (Exception e) {
            MessageUtils.showErrorMessage("Ha ocurrido Error al llenar el ComboBox: " + e.getMessage());
        }
    }
    
    public void clear() {
        jTextFieldDocument.setText("");
        jTextFieldFullName.setText("");
        jTextFieldAddress.setText("");
        jTextFieldPhone.setText("");
        jComboBoxType_id.setSelectedIndex(0);
        jButtonInsert.setEnabled(true);
        jButtonDelete.setEnabled(false);
        jButtonUpdate.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCleart;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxType_id;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelBackGround;
    private javax.swing.JLabel jLabelCloseWindow;
    private javax.swing.JLabel jLabelDescript;
    private javax.swing.JLabel jLabelDocument;
    private javax.swing.JLabel jLabelFullName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelType_id;
    private javax.swing.JLabel jLabeltTitle;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelCloseWindow;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployee;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldDocument;
    private javax.swing.JTextField jTextFieldFullName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
